set_system_time:
  name: Set System Time
  description: Set the system time.
  target:
    entity:
      domain: climate

boost_hot_water:
  name: Boost Hotwater
  description: Set the boost mode ON defining the period of time for the boost.
  fields:
    entity_id:
      name: Entity ID
      description: Select entity_id to boost.
      required: true
      selector:
        entity:
          integration: heatmiser_netmonitor
          domain: water_heater
    time_period:
      name: Time Period
      description: Set the time period for the boost.
      required: true
      example: 01:00:00
      selector:
        time:

set_holiday:
  name: Set Holiday
  description: Set a holiday.
  target:
    entity:
      domain: climate
  fields:
    start_date_time:
      example: "2022-03-22 20:00:00"
      description: Start date and time of the holiday.
      required: true
      selector:
        datetime:
    end_date_time:
      name: End Datetime
      description: End date and time of the holiday.
      example: "2022-03-22 20:00:00"
      required: true
      selector:
        datetime:
    away:
      name: Away
      description: Is the holiday period for home or away.
      required: true
      selector:
        boolean:
